const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const source = fs.readFileSync(path.join(__dirname, '..', 'routes', 'templates.js'), 'utf8')
const authSource = fs.readFileSync(path.join(__dirname, '..', 'middleware', 'auth.js'), 'utf8')

test('rich template routes remain owner/admin-only and workspace scoped', () => {
  assert.match(source, /router\.post\('\/', requireAdmin, parseTemplateUpload/)
  assert.match(source, /router\.post\('\/send', requireAdmin, parseTemplateUpload/)
  assert.match(source, /router\.delete\('\/', requireAdmin/)
  assert.match(source, /const result = await loadTemplates\(req\.workspace\.customerId\)/)
  assert.match(source, /validHeaderMedia\(file, headerType\)/)
  assert.match(source, /templateName: template\.name/)
  assert.match(authSource, /\['owner', 'admin'\]\.includes\(req\.workspace\.role\)/)
  assert.doesNotMatch(source, /body\.waba/i)
  assert.doesNotMatch(source, /body\.phone_number_id/i)
  assert.doesNotMatch(source, /body\.access_token/i)
  assert.doesNotMatch(source, /body\.components/i)
})
