const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const source = fs.readFileSync(path.join(__dirname, '..', 'routes', 'templates.js'), 'utf8')
const authSource = fs.readFileSync(path.join(__dirname, '..', 'middleware', 'auth.js'), 'utf8')

test('template routes derive WABA and phone data only from the active workspace-owned connection', () => {
  assert.match(source, /\.eq\('customer_id', customerId\)/)
  assert.match(source, /\.eq\('status', 'connected'\)/)
  assert.match(source, /router\.post\('\/', requireAdmin/)
  assert.match(source, /router\.post\('\/send', requireAdmin/)
  assert.match(source, /const allowed = \['name', 'category', 'language', 'body', 'variable_examples'\]/)
  assert.match(source, /wabaId: resolved\.number\.whatsapp_business_account_id/)
  assert.doesNotMatch(source, /body\.waba/i)
  assert.doesNotMatch(source, /body\.phone_number_id/i)
  assert.doesNotMatch(source, /body\.access_token/i)
  assert.doesNotMatch(source, /body\.components/i)
})

test('template deletion is owner/admin-only and uses a live workspace-scoped Meta selector', () => {
  assert.match(source, /router\.delete\('\/', requireAdmin/)
  assert.match(source, /const result = await loadTemplates\(req\.workspace\.customerId\)/)
  assert.match(source, /result\.templates\.find\(\(item\) => String\(item\.id\) === body\.template_id\)/)
  assert.match(source, /templateName: template\.name/)
  assert.match(authSource, /\['owner', 'admin'\]\.includes\(req\.workspace\.role\)/)
  assert.doesNotMatch(source, /body\.waba/i)
  assert.doesNotMatch(source, /body\.phone_number_id/i)
  assert.doesNotMatch(source, /body\.access_token/i)
})
