const VERSION = 1

const CATALOG = [
  { id:'welcome_message', title:'Welcome Message', description:'Greet a customer the first time they message this WhatsApp number.', category:'Engagement', industries:[], goals:[], automation_type:'welcome', availability:'available', suggested_phrases:[], suggested_response:'Hello! Thanks for contacting us. How can we help today?', content_library_supported:true, required_capability:'Welcome delivery tracking', setup_fields:['response','content'], duplicate_strategy:'single', recommendation_baseline:true, limitations:'Sent once per contact for this workspace WhatsApp number.' },
  { id:'away_message', title:'Away Message', description:'Reply when a customer messages outside your configured business hours.', category:'Operations', industries:[], goals:[], automation_type:'away', availability:'available', suggested_phrases:[], suggested_response:'Thanks for your message. We are currently away and will get back to you during business hours.', content_library_supported:true, required_capability:'Business hours', setup_fields:['response','content','timezone','hours'], duplicate_strategy:'single', recommendation_baseline:true, limitations:'This is an inbound reply, not a scheduled message.' },
  { id:'faq_response', title:'FAQ Response', description:'Answer a common customer question using phrases you choose.', category:'Customer Service', industries:[], goals:['customer_support'], automation_type:'faq', availability:'available', suggested_phrases:['what are your hours?'], suggested_response:'Our team will be happy to help. Please let us know what you need.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['topic','phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:true, limitations:'Matches the exact phrases you configure.' },
  { id:'human_handoff', title:'Human Handoff', description:'Pause automation and put a conversation in your Team Inbox.', category:'Customer Service', industries:[], goals:['customer_support'], automation_type:'human_handoff', availability:'available', suggested_phrases:['speak to a person','talk to someone'], suggested_response:'', content_library_supported:false, required_capability:'Team Inbox', setup_fields:['phrases','priority'], duplicate_strategy:'phrase', recommendation_baseline:true, limitations:'Automation stays paused while a team member handles the conversation.' },
  { id:'business_hours', title:'Business Hours', description:'Tell customers when your business is open.', category:'Customer Service', industries:[], goals:['customer_support'], automation_type:'faq', availability:'available', suggested_phrases:['hours','opening hours','business hours'], suggested_response:'Our business hours are available here. We look forward to helping you.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:true, limitations:'Use your workspace business-hours settings for after-hours replies.' },
  { id:'location_directions', title:'Location & Directions', description:'Share where customers can find your business.', category:'Customer Service', industries:[], goals:[], automation_type:'faq', availability:'available', suggested_phrases:['location','directions','where are you located'], suggested_response:'We can share our location and directions with you.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Add your address or map link in the response or Content Library.' },
  { id:'contact_information', title:'Contact Information', description:'Share the best way for a customer to contact your team.', category:'Customer Service', industries:[], goals:[], automation_type:'faq', availability:'available', suggested_phrases:['contact','phone number','email address'], suggested_response:'Here are the best ways to contact our team.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Keep your contact details current.' },
  { id:'product_enquiry', title:'Product Enquiry', description:'Reply to customers asking about products.', category:'Sales & Leads', industries:['retail','food','manufacturing'], goals:['orders','marketing_promotions'], automation_type:'keyword', availability:'available', suggested_phrases:['products','what do you sell'], suggested_response:'Thanks for your interest in our products. Tell us what you are looking for and our team can help.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'This gives information; it does not collect an order.' },
  { id:'service_enquiry', title:'Service Enquiry', description:'Reply to customers asking about your services.', category:'Sales & Leads', industries:['beauty','wellness','professional services','automotive'], goals:['lead_follow_up','customer_support'], automation_type:'keyword', availability:'available', suggested_phrases:['services','what services do you offer'], suggested_response:'Thanks for your enquiry. Tell us which service you need and our team will help.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'This is an information reply, not a booking flow.' },
  { id:'speak_to_sales', title:'Speak to Sales', description:'Send sales enquiries to your team.', category:'Sales & Leads', industries:['automotive','professional services','real estate'], goals:['lead_follow_up'], automation_type:'human_handoff', availability:'available', suggested_phrases:['speak to sales','sales'], suggested_response:'', content_library_supported:false, required_capability:'Team Inbox', setup_fields:['phrases','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Pauses automation and waits for a team member.' },
  { id:'promotion_interest', title:'Promotion Interest Reply', description:'Reply when customers ask about a promotion.', category:'Engagement', industries:[], goals:['marketing_promotions'], automation_type:'keyword', availability:'available', suggested_phrases:['promotion','special offer'], suggested_response:'Thanks for your interest in our promotion. Our team will share the current details.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Use current promotion details in your response or Content Library.' },
  { id:'price_list_link', title:'Price List / Catalogue Link', description:'Share a price list or catalogue link with customers.', category:'Sales & Leads', industries:['retail','food','manufacturing'], goals:['orders','marketing_promotions'], automation_type:'keyword', availability:'available', suggested_phrases:['price list','catalogue','prices'], suggested_response:'Here is our current price list and catalogue.', content_library_supported:true, required_capability:'Content Library link', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Use an active Text or Link Content Library item.' },
  { id:'school_fees', title:'School Fees Enquiry', description:'Give general information about school fees.', category:'Industry Templates', industries:['education','school'], goals:['customer_support','payments_collections'], automation_type:'faq', availability:'available', suggested_phrases:['fees','school fees'], suggested_response:'Thank you for your fees enquiry. Our team will share the current fee information.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'This is a static enquiry response, not payment collection.' },
  { id:'admissions_enquiry', title:'Admissions Enquiry', description:'Give a static response to admissions questions.', category:'Industry Templates', industries:['education','school'], goals:['customer_support'], automation_type:'faq', availability:'available', suggested_phrases:['admissions','enrolment'], suggested_response:'Thank you for your admissions enquiry. Our team will share the next steps.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'This is a static enquiry response, not an application flow.' },
  { id:'parent_school_info', title:'Parent / School Information', description:'Share information for parents and guardians.', category:'Industry Templates', industries:['education','school'], goals:['customer_updates'], automation_type:'faq', availability:'available', suggested_phrases:['parent information','school information'], suggested_response:'We are happy to share the information you need as a parent or guardian.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Keep the response current for your school.' },
  { id:'vehicle_service', title:'Vehicle Service Enquiry', description:'Reply to a vehicle service enquiry or send it to your team.', category:'Industry Templates', industries:['automotive'], goals:['lead_follow_up'], automation_type:'keyword', availability:'available', suggested_phrases:['vehicle service','car service'], suggested_response:'Thanks for your vehicle service enquiry. Tell us your vehicle and service need, and our team will help.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Static response only; it does not create a repair booking.' },
  { id:'respray_enquiry', title:'Respray Enquiry', description:'Reply to a respray enquiry or direct it to a team member.', category:'Industry Templates', industries:['automotive'], goals:['lead_follow_up'], automation_type:'keyword', availability:'available', suggested_phrases:['respray','paint job'], suggested_response:'Thanks for your respray enquiry. Our team can help with the next steps.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Static response only; it does not provide a quote.' },
  { id:'product_order', title:'Product Order Enquiry', description:'Explain how a customer can place an order or reach your team.', category:'Industry Templates', industries:['retail','food','manufacturing'], goals:['orders'], automation_type:'keyword', availability:'available', suggested_phrases:['order','place an order'], suggested_response:'Thanks for your order enquiry. Our team will help you with ordering information.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Static ordering information only; it does not place an order.' },
  { id:'property_enquiry', title:'Property Enquiry', description:'Reply to property enquiries or direct them to your team.', category:'Industry Templates', industries:['real estate','property'], goals:['lead_follow_up'], automation_type:'keyword', availability:'available', suggested_phrases:['property','house for sale'], suggested_response:'Thanks for your property enquiry. Our team will help with the available information.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'Static information only; it does not schedule a viewing.' },
  { id:'loan_enquiry', title:'Loan Enquiry', description:'Give general loan information or direct the customer to your team.', category:'Industry Templates', industries:['financial services','lending','loan'], goals:['lead_follow_up'], automation_type:'keyword', availability:'available', suggested_phrases:['loan','financing'], suggested_response:'Thanks for your loan enquiry. Our team can share general information and next steps.', content_library_supported:true, required_capability:'Exact phrase matching', setup_fields:['phrases','response','content','priority'], duplicate_strategy:'phrase', recommendation_baseline:false, limitations:'General information only; it is not an application or approval flow.' },
  ...['Request a Quote','Capture Customer Details','Lead Qualification','Appointment Enquiry / Booking','Booking Request','Reschedule Request','Cancellation Request','Spa Booking','Vehicle Repair Quote','Payment Reminder','Appointment Reminder','Follow-up After Enquiry'].map((title, index) => ({ id:'coming_soon_' + (index + 1), title, description:'This workflow needs a capability that is not available yet.', category: title.includes('Booking') || title.includes('Appointment') || title.includes('Spa') ? 'Bookings' : title.includes('Reminder') || title.includes('Follow-up') ? 'Operations' : 'Sales & Leads', industries:[], goals:[], automation_type:null, availability:'coming_soon', suggested_phrases:[], suggested_response:'', content_library_supported:false, required_capability:'Future workflow runtime', setup_fields:[], duplicate_strategy:'none', recommendation_baseline:false, limitations:'Coming soon — no setup or activation is available.' }))
]

function normalize(value) { return String(value || '').trim().toLowerCase() }
function getTemplate(id, version = VERSION) {
  const item = CATALOG.find((template) => template.id === id)
  return item && Number(version) === VERSION ? { ...item, version: VERSION } : null
}
function templates() { return CATALOG.map((item) => ({ ...item, version: VERSION })) }
function recommend({ industry, goals }) {
  const normalizedIndustry = normalize(industry)
  const wanted = new Set((Array.isArray(goals) ? goals : []).map(normalize))
  return templates().filter((item) => item.availability === 'available').map((item) => {
    const industryMatch = item.industries.some((value) => normalizedIndustry === normalize(value))
    const goalMatches = item.goals.filter((value) => wanted.has(normalize(value)))
    const score = (industryMatch ? 3 : 0) + goalMatches.length * 2 + (item.recommendation_baseline ? 1 : 0)
    const reason = industryMatch ? 'Recommended for your industry' : goalMatches.length ? 'Matches your setup goals' : 'A useful first automation'
    return { ...item, recommendation_score: score, recommendation_reason: reason }
  }).filter((item) => item.recommendation_score > 0).sort((a,b) => b.recommendation_score - a.recommendation_score || a.title.localeCompare(b.title)).slice(0, 6)
}
function validateProvenance({ id, version, automation_type }) {
  if (!id && !version) return null
  if (!id || !version) throw new Error('Automation template provenance is invalid')
  const template = getTemplate(id, version)
  if (!template || template.availability !== 'available' || template.automation_type !== automation_type) throw new Error('Automation template provenance is invalid')
  return template
}
module.exports = { VERSION, templates, getTemplate, recommend, validateProvenance }